#!/usr/bin/env python3
"""Audit: does every C# script under Assets/Scripts have a class-level /// doc comment
immediately above its first top-level type declaration?"""
import os, re

ROOT = r"E:\Users\Migue\Documents\GitHub\Randomiz\Assets\Scripts"
TYPE_RE = re.compile(
    r'^\s*(?:\[[^\]]*\]\s*)*(?:public|internal|private|protected|sealed|abstract|static|partial|\s)*'
    r'\b(class|struct|interface|enum)\s+([A-Za-z_]\w*)')
ATTR_RE = re.compile(r'^\s*\[')

files = []
for dp, _, fns in os.walk(ROOT):
    for fn in fns:
        if fn.endswith(".cs"):
            files.append(os.path.join(dp, fn))
files.sort()

documented = 0
generated = 0
stubs = []      # files with no top-level type (empty placeholders / GUID stubs)
undoc = []

for f in files:
    try:
        lines = open(f, encoding="utf-8-sig").read().splitlines()
    except UnicodeDecodeError:
        lines = open(f, encoding="latin-1").read().splitlines()
    text = "\n".join(lines)

    if "<auto-generated" in text or os.path.basename(f) == "myInputs.cs":
        generated += 1
        continue

    ti = None
    for i, l in enumerate(lines):
        m = TYPE_RE.match(l)
        if m and "namespace" not in l:
            ti = i
            break

    if ti is None:
        # No type declaration at all: empty placeholder / GUID-preserving stub.
        # Cannot carry a class doc comment, so it is exempt rather than undocumented.
        stubs.append(f)
        continue

    j = ti - 1
    doc = False
    while j >= 0:
        s = lines[j].strip()
        if s == "" or ATTR_RE.match(lines[j]):
            j -= 1
            continue
        if s.startswith("///"):
            doc = True
        break

    if doc:
        documented += 1
    else:
        undoc.append(f)

codescripts = len(files) - generated - len(stubs)
print("Skripte gesamt:         %d" % len(files))
print("  davon generiert:      %d (ausgenommen)" % generated)
print("  davon Leer-Stubs:     %d (ausgenommen)" % len(stubs))
print("Code-Skripte mit Typ:   %d" % codescripts)
print("  mit Klassen-Doc:      %d" % documented)
print("  OHNE Klassen-Doc:     %d" % len(undoc))
for f in stubs:
    print("  [stub] " + os.path.relpath(f, ROOT).replace(os.sep, "/"))
if undoc:
    print("\nNoch offen:")
    for f in undoc:
        print("  " + os.path.relpath(f, ROOT).replace(os.sep, "/"))
else:
    print("\n>>> Alle Code-Skripte sind dokumentiert. <<<")
